disabled_rules:
 - identifier_name
 # - file_length
 # - line_length
 - type_body_length
 - cyclomatic_complexity
 - function_body_length
 - type_name
 - shorthand_operator
 - large_tuple
 - function_parameter_count
 - unneeded_break_in_switch
 - multiple_closures_with_trailing_closure
 - inclusive_language

opt_in_rules:
 - force_unwrapping
 #- force_cast
 - force_try

#force_cast: error
force_try: error
force_unwrapping: error
line_length:
    warning: 140
    error: 200
 
excluded:
- Carthage
- Pods
- Shared/PresentationLayer/Utils/Camera/SmileMe/SmileMeCameraViewController.swift
- Shared/Extension/OSLog+Extension.swift
- Shared/PresentationLayer/Utils/WebView/AccountWebView.swift
- Shared/KeyChain/KeyChainService.swift

reporter: "xcode"
